version: '3.8'

services:
  frontend_react:
    build:
      context: ./frontend/build
      args:
        - NODE_VER=16.17.1-slim
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
    container_name: webapptemp_frontend_ct
    volumes:
      - ${PWD}/frontend:/usr/src/app/
      - /tmp/.X11-unix/:/tmp/.X11-unix
    environment:
      - HTTP_PROXY=$HTTP_PROXY
      - http_proxy=$http_proxy
      - HTTPS_PROXY=$HTTPS_PROXY
      - https_proxy=$https_proxy
      - VITE_APP_IP=$VITE_APP_IP
    ports:
      - "6600:6600"
    stdin_open: true
    tty: true

    # command: sh -c "npm install && npm run dev"

  backend_flask:
    build:
      context: ./backend/build
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
    container_name: webapptemp_backend_ct
    privileged: true
    volumes:
      - ${PWD}/backend:/home/ubuntu/workspace
      - /tmp/.X11-unix/:/tmp/.X11-unix
    environment:
      HTTP_PROXY: ${HTTP_PROXY}
      http_proxy: ${http_proxy}
      HTTPS_PROXY: ${HTTPS_PROXY}
      https_proxy: ${https_proxy}
      TZ: Asia/Tokyo
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: '1'
    devices:
      - /dev/video0:/dev/video0:mwr
    ports:
      - "6601:6601"
    shm_size: '2gb'
    stdin_open: true
    tty: true

    # command: sh -c "python server.py"

